module.exports = {
  plugins: ["testing-library", "jest-dom", "plt-rules", "unused-imports"],
  extends: [
    "plugin:testing-library/recommended",
    "plugin:jest-dom/recommended",
    "plugin:@typescript-eslint/recommended",
    "prettier/@typescript-eslint",
    "next/core-web-vitals",
    "plugin:prettier/recommended",
  ],
  settings: {
    react: {
      version: "detect",
    },
  },
  rules: {
    "plt-rules/prefer-logical": 2,
    "plt-rules/no-interpolated-classes": 2,
    "prettier/prettier": "warn",
    "@next/next/no-img-element": 0,
    "unused-imports/no-unused-imports": "error",
    "import/no-named-as-default": 0,
  },
  overrides: [
    {
      files: "*.none",
      extends: ["eslint:recommended", "plugin:react/recommended"],
      rules: {
        "array-callback-return": "error",
        "constructor-super": "error",
        "for-direction": "error",
        "getter-return": ["error", { allowImplicit: true }],
        "no-async-promise-executor": "error",
        "no-await-in-loop": "error",
        "no-class-assign": "error",
        "no-compare-neg-zero": "error",
        "no-cond-assign": ["error", "always"],
        "no-const-assign": "error",
        "no-constant-binary-expression": "error",
        "no-constant-condition": ["error", { checkLoops: true }],
        "no-constructor-return": "error",
        "no-control-regex": "off",
        "no-debugger": "error",
        "no-dupe-args": "error",
        "no-dupe-class-members": "error",
        "no-dupe-else-if": "error",
        "no-dupe-keys": "error",
        "no-duplicate-case": "error",
        "no-duplicate-imports": ["error", { includeExports: true }],
        "no-empty-character-class": "off",
        "no-empty-pattern": "error",
        "no-ex-assign": "error",
        "no-fallthrough": "error",
        "no-func-assign": "error",
        "no-import-assign": "error",
        "no-inner-declarations": "off",
        "no-invalid-regexp": "off",
        "no-irregular-whitespace": "off",
        "no-loss-of-precision": "off",
        "no-misleading-character-class": "off",
        "no-new-symbol": "error",
        "no-obj-calls": "error",
        "no-promise-executor-return": "error",
        "no-prototype-builtins": "error",
        "no-self-assign": ["error", { props: true }],
        "no-self-compare": "error",
        "no-setter-return": "error",
        "no-sparse-arrays": "off",
        "no-template-curly-in-string": "error",
        "no-this-before-super": "error",
        "no-undef": ["error", { typeof: true }],
        "no-unexpected-multiline": "error",
        "no-unmodified-loop-condition": "error",
        "no-unreachable": "error",
        "no-unreachable-loop": "error",
        "no-unsafe-finally": "error",
        "no-unsafe-negation": "off",
        "no-unsafe-optional-chaining": [
          "error",
          { disallowArithmeticOperators: false },
        ],
        "no-unused-private-class-members": "error",
        "no-unused-vars": [
          "error",
          {
            vars: "all",
            args: "after-used",
            ignoreRestSiblings: false,
            caughtErrors: "all",
          },
        ],
        "no-use-before-define": "error",
        "no-useless-backreference": "off",
        "require-atomic-updates": "error",
        "use-isnan": [
          "error",
          {
            enforceForSwitchCase: true,
            enforceForIndexOf: true,
          },
        ],
        "valid-typeof": ["error", { requireStringLiterals: true }],
        "no-nested-ternary": "error",
        "no-negated-condition": "off",
        "no-multi-str": "off",
        "no-multi-assign": ["error", { ignoreNonDeclaration: false }],
        "no-mixed-operators": "off",
        "no-magic-numbers": [
          "warn",
          {
            ignore: [0, 1],
            ignoreArrayIndexes: true,
            ignoreDefaultValues: true,
            enforceConst: false,
            detectObjects: false,
          },
        ],
        "no-loop-func": "off",
        "no-lonely-if": "error",
        "no-lone-blocks": "off",
        "no-labels": "off",
        "no-label-var": "error",
        "no-iterator": "error",
        "no-invalid-this": "off",
        "no-inline-comments": "off",
        "no-implied-eval": "error",
        "no-implicit-globals": "off",
        "no-implicit-coercion": [
          "error",
          {
            boolean: true,
            number: true,
            string: true,
            disallowTemplateShorthand: false,
          },
        ],
        "no-global-assign": "error",
        "no-floating-decimal": "error",
        "no-extra-semi": "error",
        "no-extra-label": "error",
        "no-extra-boolean-cast": "off",
        "no-extra-bind": "error",
        "no-extend-native": "error",
        "no-eval": "error",
        "no-eq-null": "error",
        "no-empty-function": "error",
        "no-empty": ["error", { allowEmptyCatch: false }],
        "no-else-return": ["error", { allowElseIf: true }],
        "no-div-regex": "off",
        "no-new": "error",
        "no-new-func": "error",
        "no-new-object": "error",
        "no-new-wrappers": "error",
        "no-nonoctal-decimal-escape": "off",
        "no-octal": "error",
        "no-octal-escape": "error",
        "no-param-reassign": ["error", { props: false }],
        "no-plusplus": "off",
        "no-proto": "error",
        "no-redeclare": ["error", { builtinGlobals: true }],
        "no-regex-spaces": "off",
        "no-restricted-exports": "off",
        "no-restricted-globals": "off",
        "no-restricted-imports": "off",
        "no-restricted-properties": "off",
        "no-restricted-syntax": "off",
        "no-return-assign": ["error", "always"],
        "no-return-await": "off",
        "no-script-url": "error",
        "no-sequences": ["error", { allowInParentheses: false }],
        "no-shadow": "error",
        "no-shadow-restricted-names": "error",
        "no-ternary": "off",
        "no-throw-literal": "error",
        "no-undef-init": "error",
        "no-undefined": "off",
        "no-underscore-dangle": "off",
        "no-unneeded-ternary": ["error", { defaultAssignment: true }],
        "no-unused-expressions": [
          "error",
          {
            allowShortCircuit: true,
            allowTernary: true,
            allowTaggedTemplates: false,
            enforceForJSX: false,
          },
        ],
        "no-unused-labels": "error",
        "no-useless-call": "off",
        "no-useless-catch": "error",
        "no-useless-computed-key": ["error", { enforceForClassMembers: true }],
        "no-useless-concat": "off",
        "no-useless-constructor": "off",
        "no-useless-escape": "off",
        "no-useless-rename": "off",
        "no-useless-return": "error",
        "no-var": "error",
        "no-void": ["error", { allowAsStatement: false }],
        "no-warning-comments": "off",
        "no-with": "off",
        "object-shorthand": "off",
        "one-var": "off",
        "one-var-declaration-per-line": "off",
        "operator-assignment": ["error", "never"],
        "prefer-arrow-callback": [
          "error",
          {
            allowNamedFunctions: false,
            allowUnboundThis: false,
          },
        ],
        "prefer-const": [
          "error",
          {
            destructuring: "all",
            ignoreReadBeforeAssign: true,
          },
        ],
        "prefer-destructuring": "off",
        "prefer-exponentiation-operator": "off",
        "prefer-named-capture-group": "off",
        "prefer-numeric-literals": "warn",
        "prefer-object-has-own": "error",
        "prefer-object-spread": "error",
        "prefer-promise-reject-errors": "off",
        "prefer-regex-literals": "off",
        "prefer-rest-params": "error",
        "prefer-spread": "off",
        "prefer-template": "error",
        "quote-props": ["error", "as-needed"],
        radix: ["error", "as-needed"],
        "require-await": "error",
        "require-unicode-regexp": "off",
        "require-yield": "error",
        "sort-imports": "off",
        "sort-keys": "off",
        "sort-vars": "off",
        "spaced-comment": ["error", "always"],
        strict: "off",
        "symbol-description": "off",
        "vars-on-top": "off",
        yoda: "off",
        "no-delete-var": "error",
        "no-continue": "off",
        "no-console": "warn",
        "no-confusing-arrow": "off",
        "no-case-declarations": "off",
        "no-caller": "error",
        "no-bitwise": "off",
        "no-array-constructor": "error",
        "no-alert": "error",
        "new-cap": "error",
        "multiline-comment-style": "off",
        "max-statements": "off",
        "max-params": "off",
        "max-nested-callbacks": "off",
        "max-lines-per-function": "off",
        "max-lines": "off",
        "max-depth": "off",
        "max-classes-per-file": "off",
        "init-declarations": "off",
        "id-match": "off",
        "id-denylist": "off",
        "guard-for-in": "off",
        "grouped-accessor-pairs": "off",
        "func-style": ["error", "expression"],
        "func-names": ["error", "as-needed", { generators: "as-needed" }],
        "func-name-matching": "off",
        eqeqeq: ["error", "smart"],
        "dot-notation": "error",
        "default-param-last": "off",
        "default-case-last": "off",
        "default-case": "error",
        curly: "error",
        "consistent-this": "off",
        "consistent-return": "off",
        complexity: "off",
        "class-methods-use-this": "off",
        "capitalized-comments": "off",
        camelcase: "off",
        "block-scoped-var": "error",
        "arrow-body-style": ["error", "always"],
        "accessor-pairs": "off",
        "react/boolean-prop-naming": [
          "error",
          { rule: "^(is|has|did)[A-Z]([A-Za-z0-9]?)+" },
        ],
        "react/button-has-type": "error",
        "react/destructuring-assignment": ["error", "always"],
        "react/display-name": "off",
        "react/forbid-component-props": "off",
        "react/forbid-dom-props": "off",
        "react/forbid-elements": "off",
        "react/forbid-foreign-prop-types": "off",
        "react/forbid-prop-types": "off",
        "react/function-component-definition": [
          "error",
          {
            namedComponents: "arrow-function",
            unnamedComponents: "arrow-function",
          },
        ],
        "react/jsx-boolean-value": ["error", "never"],
        "react/jsx-child-element-spacing": "error",
        "react/jsx-closing-bracket-location": ["error", "tag-aligned"],
        "react/jsx-closing-tag-location": "error",
        "react/jsx-curly-brace-presence": ["error", "never"],
        "react/jsx-curly-newline": ["error", "consistent"],
        "react/jsx-curly-spacing": ["error", { when: "never", children: true }],
        "react/jsx-equals-spacing": ["error", "never"],
        "react/jsx-filename-extension": [
          "error",
          { extensions: [".ts", ".tsx"] },
        ],
        "react/jsx-first-prop-new-line": ["error", "multiline"],
        "react/jsx-fragments": ["error", "syntax"],
        "react/jsx-handler-names": "off",
        "react/jsx-indent-props": ["error", 4],
        "react/jsx-indent": "error",
        "react/jsx-key": "error",
        "react/jsx-max-depth": "off",
        "react/jsx-max-props-per-line": "error",
        "react/jsx-no-bind": "off",
        "react/jsx-no-comment-textnodes": "off",
        "react/jsx-no-duplicate-props": ["error", { ignoreCase: true }],
        "react/jsx-no-literals": "off",
        "react/jsx-no-script-url": "error",
        "react/jsx-no-target-blank": "error",
        "react/jsx-no-undef": "error",
        "react/jsx-no-useless-fragment": "error",
        "react/jsx-one-expression-per-line": "error",
        "react/jsx-pascal-case": "error",
        "react/jsx-props-no-multi-spaces": "error",
        "react/jsx-props-no-spreading": "off",
        "react/jsx-sort-default-props": "off",
        "react/jsx-sort-props": [
          "error",
          {
            callbacksLast: true,
            shorthandFirst: true,
            ignoreCase: true,
            reservedFirst: false,
          },
        ],
        "react/jsx-tag-spacing": "error",
        "react/jsx-uses-react": "error",
        "react/jsx-uses-vars": "error",
        "react/jsx-wrap-multilines": "error",
        "react/no-access-state-in-setstate": "error",
        "react/no-array-index-key": "off",
        "react/no-children-prop": "error",
        "react/no-danger-with-children": "error",
        "react/no-danger": "off",
        "react/no-deprecated": "error",
        "react/no-did-mount-set-state": "error",
        "react/no-did-update-set-state": "error",
        "react/no-direct-mutation-state": "error",
        "react/no-find-dom-node": "error",
        "react/no-is-mounted": "error",
        "react/no-multi-comp": "off",
        "react/no-redundant-should-component-update": "error",
        "react/no-render-return-value": "error",
        "react/no-set-state": "error",
        "react/no-string-refs": "error",
        "react/no-this-in-sfc": "error",
        "react/no-typos": "off",
        "react/no-unescaped-entities": "error",
        "react/no-unknown-property": "error",
        "react/no-unsafe": "error",
        "react/no-unused-prop-types": "off",
        "react/no-unused-state": "error",
        "react/no-will-update-set-state": "error",
        "react/prefer-es6-class": "error",
        "react/prefer-read-only-props": "off",
        "react/prefer-stateless-function": "error",
        "react/prop-types": "off",
        "react/react-in-jsx-scope": "off",
        "react/require-default-props": "off",
        "react/require-optimization": "off",
        "react/require-render-return": "error",
        "react/self-closing-comp": "error",
        "react/sort-comp": "off",
        "react/sort-prop-types": "off",
        "react/state-in-constructor": "off",
        "react/static-property-placement": "off",
        "react/style-prop-object": "error",
        "react/void-dom-elements-no-children": "error",
        "yield-star-spacing": "off",
        "wrap-regex": "error",
        "wrap-iife": ["error", "inside"],
        "unicode-bom": "off",
        "template-tag-spacing": "off",
        "template-curly-spacing": "error",
        "switch-colon-spacing": [
          "error",
          {
            after: true,
            before: false,
          },
        ],
        "space-unary-ops": "error",
        "space-infix-ops": "error",
        "space-in-parens": ["error", "never"],
        "space-before-function-paren": ["error", "always"],
        "space-before-blocks": "error",
        "semi-style": ["error", "last"],
        "semi-spacing": "error",
        semi: "error",
        "rest-spread-spacing": ["error", "never"],
        quotes: [
          "error",
          "single",
          {
            avoidEscape: true,
            allowTemplateLiterals: true,
          },
        ],
        "padded-blocks": ["error", "never"],
        "operator-linebreak": ["error", "after"],
        "object-property-newline": "error",
        "object-curly-spacing": ["error", "always"],
        "object-curly-newline": ["error", "always"],
        "nonblock-statement-body-position": ["error", "beside"],
        "no-whitespace-before-property": "error",
        "no-trailing-spaces": "error",
        "no-tabs": "off",
        "no-multiple-empty-lines": ["error", { max: 3 }],
        "no-multi-spaces": "error",
        "no-mixed-spaces-and-tabs": "error",
        "no-extra-parens": "off",
        "newline-per-chained-call": ["error", { ignoreChainWithDepth: 2 }],
        "new-parens": "off",
        "multiline-ternary": "off",
        "max-statements-per-line": ["error", { max: 1 }],
        "max-len": "off",
        "lines-between-class-members": ["error", "always"],
        "lines-around-comment": "off",
        "linebreak-style": "off",
        "line-comment-position": "off",
        "keyword-spacing": ["error", { before: true }],
        "key-spacing": ["error", { beforeColon: false }],
        "jsx-quotes": ["error", "prefer-single"],
        indent: ["error", 2],
        "implicit-arrow-linebreak": ["error", "beside"],
        "generator-star-spacing": "off",
        "function-paren-newline": ["error", "multiline"],
        "function-call-argument-newline": ["error", "consistent"],
        "func-call-spacing": ["error", "never"],
        "eol-last": ["error", "always"],
        "dot-location": ["error", "property"],
        "computed-property-spacing": ["error", "never"],
        "comma-style": ["error", "last"],
        "comma-spacing": [
          "error",
          {
            before: false,
            after: true,
          },
        ],
        "comma-dangle": ["error", "never"],
        "brace-style": "error",
        "block-spacing": "error",
        "arrow-spacing": "error",
        "arrow-parens": ["error", "always"],
        "array-element-newline": ["error", "always"],
        "array-bracket-spacing": ["error", "never"],
        "array-bracket-newline": ["error", "consistent"],
      },
    },
  ],
};
